### ISSUE TITLE
how to understand triangulate process

### ISSUE THREAD

**Issue by aileenfun** [LaserBorg/LineScanner#1]
Hi:
I'm trying to understand triangulate function, is there any link or graphic example ?
thank you!

**Comment by LaserBorg** [comment]
Hi, it's a series of plane-point intersections in 3D space. each row results in a single 3D point. the laser plane is swept horizontally, so each frame is equal to a column of points and at 30 frames per second, a camera with a vertical resolution of 1080 pixels delivers around 32400 3D points per second (30 columns, 1080 rows). 

obviously the laser is not a point but a vertical line and the laser diode is supposed to be mounted on a stepper or servo motor that rotates a tiny angle after each frame is completed, but this is not yet in my code ( I guess I was just interested in solving the CV problem back then).

the link in my readme seems to be broken but you can still find it on waybackmachine:
https://web.archive.org/web/20210227064149/http://geomalgorithms.com/a05-_intersect-1.html

there is a 3D scene in this project in 3ds Max Format that I used to render the test clips. 

the code checks each frame, each row for the horizontal position of the laser, then uses the camera field-of-view and each of these XY screenspace coordinates to form 3D vectors that use their x (width) and y (height) as direction and the camera's location (0,0,0) as origin.  
this line then intersects with a plane that is described by it's normal vector (rotating each frame) and the laser's location as origin.

so each frame of the camera provides one column of points, and sweeping the laser horizontally covers the entire field of view. does that make sense to you :) ?

top view with camera and laser:
![1](https://github.com/LaserBorg/LineScanner/assets/12850910/840c5699-0dc4-43bd-a314-a0f1cbf00655)

perspective view, now you can see that the laser is actually a laser plane.
![2](https://github.com/LaserBorg/LineScanner/assets/12850910/87bc6497-6282-4c93-98a3-653c4d61c8c6)

**Comment by LaserBorg** [comment]
I just cleaned up the repo a bit and added some of the old example code snippets and experiments. It's not self-explanatory but with the context given, you might find this diagram informative:  

![triangulation](https://raw.githubusercontent.com/LaserBorg/LineScanner/main/doc/calculation.jpg)
